# Generated by Django 4.0.5 on 2022-06-09 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_app', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_user', models.CharField(max_length=50)),
                ('create_program', models.CharField(max_length=200)),
                ('modify_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_user', models.CharField(max_length=50)),
                ('modify_program', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=2000, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
